import React, { useEffect } from "react";

const TermsAndCondition = () => {
  useEffect(() => {
    // Scroll to the top of the page when the component is mounted
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="bg-gray-100 min-h-screen py-10 px-5">
      <div className="mx-auto bg-white shadow-md rounded-md w-full">
        <div className="bg-gradient-to-r from-blue-500 to-blue-700 text-white p-6 w-full rounded-t-lg">
          <h1 className="text-3xl text-white font-bold mb-6">
            Terms & Conditions
          </h1>
        </div>
        <div className="px-8">
          <p className="mb-4 mt-4">
            This document is an electronic record in terms of the Information
            Technology Act, 2000 (as may be amended, modified, re-enacted,
            consolidated, or replaced from time to time) and rules thereunder
            pertaining to electronic records as applicable and amended from time
            to time, and is published in accordance with the provisions of Rule
            3 of the Information Technology (Intermediaries Guidelines and
            Digital Media Ethics Code) Rules, 2021 (“Rules”), which mandates
            YOURSAY (as defined below) as an intermediary to publish the terms
            and conditions and other rules and regulations for access or usage
            of the Platform (as defined below). This document is generated by a
            computer system and does not require any physical or electronic
            signature.
          </p>

          <h2 className="text-xl font-semibold mb-4">1. INTRODUCTION</h2>
          <p className="mb-4">
            Welcome to the YOURSAY platform. The use of the terms ‘YOURSAY’,
            ‘We’, ‘Us’, ‘Our’ and/or ‘Company’ in these Terms and Conditions of
            Use (‘Terms’) shall refer to ASAR Gaming Network Private Limited, a
            company duly organized under the laws in India, which is engaged in
            operating the website located at
            <address>
              [1-E/3, First Floor, Block E 1, Jhandewalan Extension,
              Jhandewalan, New Delhi, Delhi 110055]
            </address>{" "}
            (‘Website’) and through mobile application(s) under the name and
            style ‘YOURSAY’ (‘Application(s)’) (collectively, the ‘Platform’).
          </p>
          <p className="mb-4">
            For the purpose of these Terms, wherever the context so requires,
            <b> ‘You’, ‘Your’, ‘Yourself’</b> and/or<b>‘User(s)’</b> (as further
            defined below) shall mean any natural or legal person(s) who
            accesses or visits the Platform (as further defined below), uses, or
            avails the Game (as defined below) and the Services offered on the
            Platform and registers or provides any information on the Platform,
            irrespective of whether such person is an individual, company or
            other entity. Any titles or headings inserted in these Terms are for
            convenience only and shall not affect the interpretation of the
            provisions of the Terms.
          </p>
          <p className="mb-4">
            Users acknowledge and understand that YOURSAY is the sole owner of
            the Platform, and these Terms govern Your access and use of all
            features, content, and other services that YOURSAY owns, controls
            and makes available through YOURSAY’s online Platform and any other
            applications, tools, products, and services that YOURSAY may provide
            from time to time on the Platform (collectively termed ‘Services’,
            as further elaborated hereunder). By visiting or accessing the
            Platform, registering and creating an Account (as defined below) on
            the Platform, using and availing the Services available on the
            Platform, providing any information on the Platform, and otherwise
            making use of the Platform, whether implicitly or expressly, You
            acknowledge and accept these Terms and enter into a binding contract
            with YOURSAY.
          </p>
          <p className="mb-4">
            YOURSAY encourages and advises all Users to read and understand
            these Terms prior to making use of the Platform and the Services.
            Your use of, and access to, the Platform and Services is subject to
            these Terms. Any usage of the Platform or Services in any manner
            whatsoever shall be governed by these Terms read with the privacy
            policy published on the Platform (‘Privacy Policy’) or any other
            policy which may be published on the Platform (collectively termed
            ‘Policies’) which shall together make up the collective agreement
            between the User and the Company.
          </p>
          <p className="mb-4">
            User(s) acknowledge and accept that User(s) shall be subject to and
            bound by the Policies, regardless of how the User(s), or anyone on
            the User’s behalf, has accessed or participated in the Game and/or
            the Platform. If the User does not want to be bound by the Terms,
            they must not retain, access and/or use the Platform or Services in
            any manner whatsoever. Anything done, caused to be done, whether
            expressly or impliedly, in contravention of these Terms, may render
            the User liable for legal action.
          </p>

          <h2 className="text-xl font-semibold mb-4">2. DEFINITIONS</h2>
          <p className="mb-4">
            For the purposes of these Terms, in addition to any words,
            expressions, or terms expressly defined in the introduction and in
            the text of these Terms, any references to the following terms,
            words, and expressions, wherever used in these Terms, unless
            repugnant to the meaning or context thereof, shall have the
            following meanings:
          </p>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              <b>‘Applicable Law(s)’</b> shall mean the applicable laws,
              statute, rule, regulation, ordinance, guideline, by-law, or
              subordinate legislation of India as well as all amendments to the
              same which come into force from time to time.
            </li>
            <li className="mb-2">
              <b>‘Platform’</b> shall mean and include the Website and
              Application(s) through which the Services are made available by
              YOURSAY.
            </li>
            <li className="mb-2">
              <b>‘Game’ </b>shall mean the online skill-based opinion trading
              game offered to User(s) on the Platform by the Company in
              accordance with the Policies, which features and includes the
              periodic Contest(s) (as defined below). It is clarified that the
              Game requires User(s) to employ their intellectual effort and
              skill in order to determine queries and outcomes of real-world
              events using their knowledge and skill and the informative
              insights and resources made available by the Company (to support
              Users in their research and decision-making process). Users may
              participate in the Game and compete against other User(s) for the
              Winnings (as defined below) by placing Trades (as defined below)
              upon registering on the Platform in accordance with the Policies;
            </li>
            <li className="mb-2">
              <b>‘Trade(s)’</b> shall mean the monetary transaction(s) placed by
              User(s) in relation to event-based questions within the Game,
              reflecting their opinion on a potential outcome. It is clarified
              that for each event-based question, Users may purchase and select
              unit(s) of either ‘Yes’ or ‘No’ based on their research and
              opinion of the event’s outcome. Users can place their Trade(s) at
              any time before the match concludes, and the Trade is executed
              when opposing opinions from different Users (i.e., one User
              selects ‘Yes’ while another selects ‘No’) are matched;
            </li>
            <li className="mb-2">
              <b>‘Prize Pool’</b> shall mean the collective sum of all amounts
              contributed by User(s) when placing their Trade(s) as part of the
              Game, which are pooled together once the Trades are matched;
            </li>
            <li className="mb-2">
              <b>‘Winning(s)’</b> shall mean the portion of the Prize Pool
              awarded to the User(s) who correctly predict the outcome of the
              event. The User(s) whose Trade(s) match the actual outcome of the
              event are declared the winner(s) and receive the corresponding
              amount from the Prize Pool as their Winnings, in accordance with
              the Terms of the Platform;
            </li>
            <li className="mb-2">
              <b>‘Contest(s)’</b>shall mean the daily contests held by the
              Company as part of the Game in a head-to-head format, as part of
              which Users answer a set of time-sensitive questions related to
              specific matchups. Upon successful registration, Users gain access
              to the Game available on the Platform, enabling them to
              participate in these contests.
            </li>
            <li className="mb-2">
              <b>‘Business Partner(s)’</b> shall mean any natural and legal
              person(s) with which YOURSAY has a business arrangement or
              collaboration under a definitive agreement, in relation to the
              functioning of the Platform and its Services, such as for
              facilitating, providing and/or delivering certain functionalities
              on the Platform including any features or aspects of any Services
              provided to User(s) on the Platform. Our Business Partners
              includes Our payment service partner(s) [Cashfree], Know Your
              Customer (KYC) and verification partner(s) [Cashfree] among other
              relevant third-party vendors;
            </li>
            <li className="mb-2">
              <b>‘Minor’</b> shall mean a child or person below the age of
              majority in the legal jurisdiction in which he/she is based, who
              is not eligible to create or register an Account on the Platform
              and/or avails any of the Services;
            </li>
            <li className="mb-2">
              <b>‘Restricted Territories’</b> shall mean and include the states
              of Assam, Andhra Pradesh, Nagaland, Orissa, Sikkim, Telangana,
              Tamil Nadu and any other relevant states or territories in India
              which impose prohibitions, restrictions and/or regulatory
              requirements (under local/state legislation) as regards provision
              of online gaming services to individuals located within the
              relevant territory;
            </li>
            <li className="mb-2">
              <b>‘User(s)’,‘You’, ‘Your’, ‘Yourself’</b> shall mean an
              individual who is resident in India, who has signed up/registered
              on the Platform and/or is participating in the Game and/or is
              availing any of the Services provided by the Platform and/or has
              access to/uses the features and functionalities of the Platform
              and who in connection with the Platform and the Services may
              access or avail, share, transact, view, display, download or
              upload any information on the Platform. A reference to User(s)
              include the person(s) referred to under clause 1 above but
              excludes any persons who is a Minor or is resident in Restricted
              Territories;
            </li>
            <li className="mb-2">
              <b>‘User Information’</b> shall mean information relating to a
              User and the User’s Account, including the personal information
              and/or other data and information mentioned in Our Privacy Policy.
              User Information may be required to be provided by User(s) to
              YOURSAY at the time of registering an Account (such as under the
              registration form required to be filled out by the User) and/or
              subsequent to the time of registration (such as at the time the
              User avails any Services on the Platform, accesses the Game or
              participates in the Contest). User Information includes any
              User-related information for which a written request may be
              communicated to the User by YOURSAY at any time in relation to the
              User(s) use of the Platform; and
            </li>
            <li className="mb-2">
              <b>‘Services’</b> shall mean the Game (including in-game Contests)
              and ancillary services (including resources, tools,
              functionalities, and other facilities) which are made available to
              User(s) through the Platform by YOURSAY upon registration of an
              Account on the Platform by a User. These include the services
              elaborated hereinbelow as well as any other tools,
              functionalities, and services that YOURSAY may provide or make
              available on the Platform from time to time.
            </li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">
            3. ELIGIBILITY AND GENERAL CONDITIONS
          </h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              By using the Platform in any manner (such as through registering
              an Account, accessing the Website or Application(s) and/or using
              or accessing the Game or any of the Services), You declare that
              You have read, understood, and accepted the provisions of these
              Terms in full and hereby agree to comply with, and be bound by,
              the Terms. You hereby agree to be bound by these Terms in respect
              of such use of the Platform and to be liable for all activities
              conducted through Your Account on the Platform. If You do not
              agree to the provisions of these Terms, You must not register an
              account, access, use the Platform in any manner such as by
              receiving any of the Services
            </li>
            <li className="mb-2">
              YOURSAY does not offer or provide Services to Minors. To be
              eligible for registration on the Platform, Users must be of legal
              age to form a binding contract and should not be barred from
              receiving Services under the laws of the applicable jurisdictions
              in which the User resides. By registering, You represent and
              undertake that you are a person of legal age to form a binding
              contract and are not a person barred from receiving Services under
              the applicable laws in India and these Terms. For avoidance of
              doubt, Minors (being persons less than eighteen years of age in
              India) are not eligible to register on the Platform and avail the
              Services. Your agreement to these Terms shall indicate that You
              have the right, authority, and legal capacity to agree to the
              Terms and that You have read, understood, and agree to be bound by
              the same.
            </li>
            <li className="mb-2">
              YOURSAY does not offer or provide Services within or to residents
              of the Restricted Territories in India. To be eligible for
              registration on the Platform, Users must not be residents of any
              Restricted States. By registering, You represent and undertake
              that You are not from any the Restricted Territories. You shall
              refrain from making any false disclosures, declarations and/or
              representations to Us to circumvent the Applicable Laws of the
              Restricted States. For avoidance of doubt, You shall be solely
              liable for any such false disclosures, declarations,
              representations and/or submissions under the Applicable Laws in
              accordance with these Terms.
            </li>
            <li className="mb-2">
              We reserve the right, at Our sole discretion, to change, modify,
              add, or remove portions of these Terms and applicable Policies.
              You acknowledge and accept that these Terms and Policies may be
              amended from time to time and such amendments will become
              effective and binding on You, from the time of their publication,
              announcement, or communication of the amendment on the Platform by
              YOURSAY. Your continued use of the Platform (and its Services)
              after such notice confirms Your consent to and acceptance of such
              amendments. It is Your responsibility to review these Terms and
              any Platform Policies periodically for updates/changes, therefore,
              You are encouraged to revisit the Platform to be updated as
              regards any amendments.
            </li>
            <li className="mb-2">
              <b>Feedback.</b> You can reach out to us using the “Contact Us”
              option(s) available on the Platform in case You have any questions
              or doubts pertaining to the YOURSAY’s Services and/or the
              Platform, or if You wish to share Your suggestions/improvements,
              experience, comments and requests as regards the same
              (collectively “Feedback”). YOURSAY welcomes any Feedback the
              User(s) might have on the Platform and Services provided, You
              acknowledge and accept that; the Feedback You may provide
              regarding YOURSAY, and/or the Services is entirely voluntary and
              YOURSAY will be free to use such Feedback as We see fit and
              without any obligation to You; YOURSAY shall not be subject to any
              obligation of confidentiality in relation to any submitted
              Feedback; and YOURSAY shall not be liable in any way for any delay
              in responding to any Feedback forwarded by You. If You provide
              Feedback, You represent, warrant, and covenant to YOURSAY that
              Your Feedback does not violate the rights, including publicity,
              intellectual property rights, personality or any other rights, of
              any person and/or third party. Further, You grant YOURSAY a
              worldwide, non-exclusive, royalty-free, perpetual, irrevocable,
              transferable, and fully sub-licensable right to use, reproduce,
              publish, distribute, publicly display, publicly perform,
              translate, adapt, modify, telecommunicate, rent out,
              commercialize, monetize, and create derivative works from the
              Feedback in any way and for any purpose without providing any
              compensation to You or any other person. You also grant YOURSAY
              the right to use the Credentials (as defined below) and other
              details You submit with the Feedback (if any) in connection with
              YOURSAY’s rights hereunder.
            </li>
            <li className="mb-2">
              However, in case You have any complaint or grievance in respect of
              any content or services provided on the Platform or any breach of
              Our Terms, Privacy Policy or any other policy published on the
              Platform (‘Grievance’), please contact Our Resident Grievance
              Officer (as defined herein below) in accordance with these Terms.
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">
            4. REGISTRATION AND USE OF SERVICES
          </h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              <b>Account Registration. </b> To enable Your access and use of the
              Services available on the Platform, You are obligated to register
              on the Platform using Your contact details (including Your name,
              email address and mobile number) (the ‘User ID’ or ‘Credentials’)
              by providing YOURSAY with the User Information and following the
              registration process of the Platform as also mentioned herein.
              Upon successful registration of a User on the Platform, the User
              becomes entitled to an exclusive virtual account with which the
              User can browse and avail the Services that may be offered or made
              available to the Users of the Platform by YOURSAY and/or through
              its Business Partners (‘Account’). You may only register and use a
              single Account with Us and may not use or access multiple Accounts
              on the Platform. The registration process for Users to create an
              Account on the Platform involves registering Credentials on the
              Platform and providing applicable User Information. Following the
              completion of the registration process, subject to appropriate
              process(es) undertaken by YOURSAY in its sole discretion, an
              acknowledgement of the activation of Your Account shall be
              communicated from YOURSAY to one or more of the contact details
              provided by You on the Platform. You may further opt to
              voluntarily verify Your Accounts by using KYC verification
              process(es) enabled on the Platform in collaboration with Our
              Business Partner(s). Where any User voluntarily verifies their
              Account, such User shall be provided with a demonstrable and
              visible mark of verification.
            </li>
            <li className="mb-2">
              <b>User Information. </b>Your User Information, including Your
              User ID, as made available to Us, is treated as Your primary
              identification on the Platform. It is re-iterated that it is Your
              responsibility to ensure that the User Information provided on the
              Platform is valid and remains updated at all times. YOURSAY is not
              liable for non-rendering of requested Services owing to any
              incorrect or invalid information that is reflected/uploaded on
              Your Account in any way. You acknowledge and agree that We may
              share User Information or any other information in Our control or
              possession with (i) appropriate authorities for the purpose of
              verification of identity or for the prevention, detection,
              investigation or prosecution of offences under any law for the
              time being or for cyber security incidents; (ii) with Business
              Partners and third parties for the purposes and in the manner
              elaborated in Our Privacy Policy. Further, We may preserve such
              information and associated records as maybe required for
              evidentiary and investigation purposes for a statutorily
              prescribed period.
            </li>
            <li className="mb-2">
              <b>Services: </b> Upon registration in accordance with these
              Terms, Users shall be eligible to avail Our Services, including by
              participating in the Game (and the in-game Contests) as well as
              availing relative facilities as may be made available by us on the
              Platform from time to time in accordance with these Terms and the
              Policies. You acknowledge and accept that certain Services and
              facilities (in relation to payment and verification) are made
              available on the Platform by YOURSAY through relevant Business
              Partner(s). You accept and acknowledge that use of the Services on
              the Platform may be subject to terms and conditions imposed by the
              applicable Business Partner(s) in addition to YOURSAY’s Terms and
              Policies
            </li>
            <li className="mb-2">
              <b>Purchases. </b> YOURSAY does not charge any fee for
              registration of an Account on the Platform, however, You are
              required to make payment to Us availing certain Services,
              including for placing Trade(s) in order to participate in the Game
              offered on the Platform. The applicable costs for the relevant
              Services will be indicated to You on the Platform, together with
              applicable service and other taxes, following the finalization of
              Your purchase
            </li>
            <li className="mb-2">
              <b>Payment. </b> For making payment transactions on the Platform,
              User(s) may use any of the payment methods available on the
              Platform provided You acknowledge and accept that the payment
              methods are made available on the Platform by Us through relevant
              Business Partner(s) (which facilitate the payments taking place on
              the Platform) and that use of such payment methods may be subject
              to terms and conditions of and/or processing fees imposed by the
              applicable Business Partner(s) in addition to Our Terms and
              Policies. You are solely responsible for all charges and usage
              associated with Your Account concerning the purchases made by You
              or anyone that uses Your Account. We shall not be liable for any
              costs incurred by the User for any third-party expenses or other
              expenditure arising out of or in connection with any transaction
              on the Platform. When You provide any financial and other details
              on the Platform for the purpose of purchases and payment through
              any payment method, You represent and warrant that You are the
              legally authorized user of the relevant payment method and are
              providing current, complete, and accurate information.
            </li>
            <li className="mb-2">
              <b>Verification. </b> Following registration, Users shall verify
              their identity prior to making any purchase(s) on the Platform.
              For this purpose, User(s) shall follow the procedures and submit
              the information and documents sought for verification by Our
              relevant Business Partner(s).
            </li>
            <li className="mb-2">
              <b>Withdrawal and Refund Policy: </b> Users are advised to review
              these Terms prior to making purchases on the Platform. YOURSAY
              does not allow withdrawals or cancellations of deposits made on
              the Platform. YOURSAY does not issue refunds for payments/Trade(s)
              placed on the Platform except in the event of Our gross technical
              failure in rendering the Services purchased by You. Should such a
              failure occur, You may request YOURSAY for refund/withdrawal of
              deposits made towards availing by contacting our support team at
              [support@yoursay.live]. We shall endeavor to promptly verify Your
              request and determine Your eligibility for refund/withdrawal. Upon
              due verification and determination, We will pro-rate the charges
              (as may be applicable) and process the refund typically within
              [14] business days. You understand and acknowledge that no refunds
              or withdrawal will be provided by Us under any other
              circumstances.
            </li>
            <li className="mb-2">
              <b>Security. </b> We protect and secure the confidentiality of
              Your Credentials and User Information using the practices and
              procedures elaborated in Our Privacy Policy. While we do not
              collect, process and store payments/deposits from User(s), We
              partner with suitable Business Partners to facilitate the
              collection, processing and storage of deposits/payments from
              User(s) for the Services offered on the Platform. Our Business
              Partner(s) employ appropriate and reasonable protocols and
              processes commiserate with industry standards in India for
              safeguarding and securely maintaining all transactions and
              deposits made by Users for Our Services.{" "}
            </li>
            <li className="mb-2">
              <b>Payout. </b> YOURSAY shall calculate and disburse payments to
              User(s) which win any Prize(s) immediately while participating in
              the Game utilizing mutually agreed payment methods. YOURSAY shall
              not be liable for any delays or failures in the payout process
              resulting from the User's failure to provide accurate and current
              contact information or to complete the verification process. Users
              accept and acknowledge that payouts may be withheld until the User
              successfully remedies such failure.{" "}
            </li>
            <li className="mb-2">
              <b>Third-Party Links. </b> The Platform may include external links
              to the third-party platform which are not under the control of the
              Company. Third-party links during the course of the Game
              (including in-game Contests) are also provided to enable Users to
              access informative insights and real-time updates for the purpose
              of gameplay. We provide these links to the third-party platforms
              to You for your convenience, however, We are not responsible for
              the content of any third-party platforms and/or any content or
              links contained in the third-party platforms. Further, YOURSAY is
              not responsible for any kind of loss/damage arising out of Your
              access to such third-party links or out of any act on such
              third-party platforms.{" "}
            </li>
            <li className="mb-2">
              <b>Promotions and Discounts: </b> Any promotions, discounts or
              deals as may be available on the Platform in relation to the
              Services from time to time shall be run subject to the Policies
              along with any specific promotional terms and conditions as may be
              published by Us on Our Platform from time to time.{" "}
            </li>
            <li className="mb-2">
              By using the Platform in any manner (such as through registering
              an Account, accessing the Website or Application(s) and/or using
              or accessing any of the Services), You represent and warrant to
              YOURSAY that You:
              <ul className="list-disc list-inside mb-6 ml-6">
                <li className="mb-2">
                  are an Indian citizen of legal age under the Applicable Law,
                  are not a resident of a Restricted State, and have the legal
                  right, capacity, and power to accept the provisions of these
                  Terms with YOURSAY in accordance with the Applicable Law;
                </li>
                <li className="mb-2">
                  have read, understood, and agree at all times to abide by the
                  provisions of these Terms as well as any other Policies
                  published on the Platform which are binding and enforceable
                  against You and will revisit the Website, from time to time,
                  to review any updates and amendments to such policies, these
                  Terms and any other Policies as may be published or updated on
                  the Platform from time;{" "}
                </li>
                <li className="mb-2">
                  are solely and entirely responsible for any activity,
                  including any act or omission, that occurs on or through Your
                  Account. This includes the responsibility of providing
                  correct, valid, complete, accurate and up-to-date User
                  Information at the time of registering an Account and at any
                  time required thereafter and ensuring that the User
                  Information is provided, maintained, and updated regularly as
                  and when necessary, in accordance with the Terms. This further
                  includes the responsibility to maintain control over, and
                  security of, Your Account, such as by not disclosing Your User
                  ID, not sharing Your Account, or allowing anyone other than
                  Yourself to access Your Account and avail Services accessible
                  under Your Account; and{" "}
                </li>
                <li className="mb-2">
                  are qualified to register an Account, access, and use the
                  Platform and Services and meet all requirements under these
                  Terms read together with the applicable Policies published on
                  the Platform (as may be updated from time to time).{" "}
                </li>
              </ul>
            </li>
            <li className="mb-2">
              YOURSAY may, in its sole and absolute discretion, at any time
              request Users for any information as it may require for
              verification of the identity of the User or to verify that the
              User is using the Platform / availing the Services in conformity
              with these Terms. If YOURSAY has reason to suspect that any Minor
              or any other User is making use of the Platform in a manner not
              permitted in these Terms, YOURSAY reserves the right to request
              further information from the relevant Account User under suspicion
              for the purpose of verification that such User and the User’s
              Account is compliant with the Terms, in the manner mentioned
              herein at its sole discretion. If We find that a relevant User /
              User Account is not in compliance with the Terms in any way, We
              further reserve the right to take suitable action against such
              User in the manner mentioned herein as We may deem fit at Our sole
              discretion, in accordance with Our Policies. It is re-iterated
              that we shall have no responsibility in case any User does not
              provide their accurate Credentials or User Information for
              accessing the Platform.
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">
            5. USER OBLIGATIONS AND RESPONSIBILITIES
          </h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              Each User acknowledges and accepts that if the relevant User
              provides any information that is untrue, inaccurate, not current
              or incomplete as part of the User Information, and/or We have
              reasonable grounds to suspect that any information provided by the
              relevant User is untrue, inaccurate, not current or incomplete, or
              not in accordance with these Terms, We have the right, at Our sole
              discretion, to (i) request You to promptly update or correct such
              User Information; and/or (ii) immediately and indefinitely suspend
              Your Account, block Your access to the Platform, terminate and/or
              delete Your Account and/or refuse to provide any current or future
              Services to You, as may be offered on the Platform. If YOURSAY is
              not satisfied with such verification or discovers any
              non-compliance by a User, YOURSAY reserves the right to take
              suitable action against the User in accordance with these Terms,
              including but not limited to refusing the registration of an
              Account by such User, or cancelling such User’s Account, or taking
              suitable legal action under the Applicable Law, in its sole
              discretion.
            </li>
            <li className="mb-2">
              You are solely responsible for security of Your Account, and
              ensuring that Your Credentials are not compromised, shared with
              anyone, or mishandled. Any loss resulting from the unauthorized
              use of Your Credentials is Your responsibility alone. If You
              suspect that an unauthorized person has become aware of Your User
              Credentials, You must change Your User Credentials forthwith, and
              immediately contact Us for assistance. You are further responsible
              for ensuring Your compliance under the Terms or any other
              applicable Policies of the Platform, including maintaining the
              security and confidentiality of Your Account and User Information,
              and Your activity on the Platform, including all and any
              activities that take place in, or occur under, or are associated
              with Your Account, and any consequences thereof. User(s)
              acknowledge and accept that the Account/Services shall not be used
              for any purposes which are prohibited under the Applicable Law,
              the Terms, or any other applicable Policies of the Platform. We
              shall not be liable for any repercussions, legal or otherwise,
              including loss or damage arising from a User(s) failure to comply
              with the same. We shall not be responsible for any unauthorized
              use of Your Account in any manner whatsoever.
            </li>
            <li className="mb-2">
              We do not publish and We do not permit Our Users to publish any
              unlawful information or content which is prohibited under these
              Terms or any law for the time being in force, including any
              content which is or is likely to be perceived as being harmful to
              interest of sovereignty and integrity of any country, security of
              India, friendly relations with foreign states, public order,
              decency or morality, amounts to contempt of court, defamation,
              incitement to an offence etc. We reserve the right to monitor Your
              Account and the Platform to ensure Your compliance with such
              Terms. Upon actual knowledge that any such information or content
              has been provided on the Platform (including in the form of
              Feedback), We shall have the right to promptly remove the same.
              Further, in such case and in any other case of any violation of
              these Terms by a User, We have the right to take appropriate
              action against the User (including at Our discretion) in
              accordance with the law. You shall be given reasonable and
              adequate opportunity to dispute the action being taken by
              addressing Your requests and complaints to Our Resident Grievance
              Officer in accordance with Our grievance redressal mechanism
              (detailed herein below).
            </li>
            <li className="mb-2">
              We do not upload or share or permit anyone to upload and share any
              information or content on the Platform and/or through use of Our
              Services that:
              <ul className="list-disc list-inside ml-6 mb-6">
                <li className="mb-2">
                  belongs to another person and to which the User does not have
                  any right to under the Applicable Law;
                </li>
                <li className="mb-2">
                  is false, misleading, fraudulent, defamatory, obscene,
                  pornographic, pedophilic, invasive of another's privacy,
                  including bodily privacy, insulting or harassing on the basis
                  of gender, libelous, racially or ethnically objectionable,
                  relating or encouraging money laundering or gambling or an
                  online game that causes user harm, or promoting enmity between
                  different groups on the grounds of religion or caste with the
                  intent to incite violence, or otherwise inconsistent with or
                  contrary to the laws in force;
                </li>
                <li className="mb-2">
                  is harmful or has a detrimental effect upon children / Minors
                  in any way;{" "}
                </li>
                <li className="mb-2">
                  infringes any patent, trademark, copyright or other
                  intellectual property and proprietary rights of any natural or
                  legal person under the Applicable Law;{" "}
                </li>
                <li className="mb-2">
                  deceives or misleads the addressee about the origin of the
                  message or knowingly and intentionally communicates any
                  misinformation or information which is patently false and
                  untrue or misleading in nature, or, which in respect of any
                  business of the Indian Government, is identified as fake or
                  false or misleading by the official fact check unit;{" "}
                </li>
                <li className="mb-2">
                  impersonates another person or use an anonymous proxy;{" "}
                </li>
                <li className="mb-2">
                  threatens the unity, integrity, defense, security or
                  sovereignty of India, friendly relations with foreign nations,
                  or public order, or causes incitement to the commission of any
                  cognizable offence or prevents investigation of any offence or
                  is insulting other nations;{" "}
                </li>
                <li className="mb-2">
                  contains software viruses or any other computer code, files or
                  programs designed to interrupt, destroy or limit the
                  functionality of any computer resource;{" "}
                </li>
                <li className="mb-2">
                  is in the nature of an online game which is subject to
                  prohibition under prevailing Applicable Law or order of any
                  competent authorities in India or is in the nature of
                  advertisement or surrogate advertisement or promotion of such
                  an online game or of any online gaming platform offering such
                  an online game; and/or{" "}
                </li>
                <li className="mb-2">
                  violates any law for the time being in force.{" "}
                </li>
              </ul>
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">6. GENERAL DISCLAIMERS</h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              YOURSAY reserves the right to add, amend or discontinue,
              temporarily or permanently, any of its Services (or any part
              thereof) offered through the Platform or the design and
              functionality of the Platform, at any time, with or without notice
              and/or reason(s) in its sole and absolute discretion. User agrees
              that YOURSAY shall not be liable either to User or to any third
              party for any modification, suspension or discontinuance of any of
              the Services including without limitation any failure of
              performance, error, omission, interruption, deletion, loss of
              information, defect, delay in operation or transmission,
              communications line failure, theft or destruction or unauthorized
              access to, alteration of, or use of records, whether for breach of
              contract, tortuous actions, negligence, or under any other cause
              or action.{" "}
            </li>
            <li className="mb-2">
              You acknowledge and accept that despite Our efforts, the Platform
              may be unavailable from time to time for any reason including,
              without limitation, routine maintenance. In addition, various
              portions of the Platform and/or Services may operate slowly from
              time to time. You further acknowledge and accept that due to
              circumstances, within and outside the control of YOURSAY, access
              to the Platform and/or Services may be interrupted, suspended, or
              terminated from time to time. In particular, and not in limitation
              of the foregoing, YOURSAY shall not be liable for the effects any
              delay or unavailability of the Platform and/or Services may have
              on You and/or Your Account, or for any damages arising from any
              such interruption, suspension, or termination of the Platform/
              Services. YOURSAY shall not bear any liability for any damage or
              interruptions caused by any computer viruses, spyware, or other
              malware that may affect Your computer or other equipment, or any
              phishing, spoofing, or other attack and We advise You to make
              regular use of a reliable virus and malware screening and
              prevention software to guard against the same.{" "}
            </li>
            <li className="mb-2">
              You agree and acknowledge that the Platform and Services is
              licensed and/or provided hereunder on an “as is” and “as
              available” basis, without any warranties of any kind, either
              express or implied including, but not limited to, the implied
              conditions and warranties of fitness for a particular purpose to
              the extent permitted by the Applicable Law. Except as explicitly
              set forth herein, neither YOURSAY and its affiliates, directors,
              officers, personnel, agents permitted successors and assigns and
              authorized representatives (‘YOURSAY Entities’), make any
              warranties of any kind, either expressed or implied, including,
              without limitation: warranties of merchantability or fitness for a
              particular purpose related to the use of Platform and/or Services;
              or that the same accurate, error-free, reliable, uninterrupted,
              that defects will be corrected; or the completeness, accuracy,
              availability, timeliness, security or reliability of the Platform
              and/or Services or the functionality of thereof, or other use or
              consequence of the use of Platform and/or Services.{" "}
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">
            7. SUSPENSION AND CANCELLATION OF USER ACCOUNT
          </h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              YOURSAY reserves the right to immediately disable or terminate or
              cancel Your Account, or suspend Your access to the Platform and/or
              Services at any time, with or without notice to You, in its sole
              and absolute discretion, in case of Your contravention or
              violation of these Terms and applicable Policies; or Your illegal
              acts or omissions; or misuse of the Services or Platform; or to
              protect You and others from identity theft or other fraudulent or
              illegal activity under the Applicable Law, or if YOURSAY is unable
              to continue providing the Services to You due to technical or
              legitimate business reasons. In the event, Your Account is
              disabled or deleted by YOURSAY due to a violation of the Terms,
              applicable Policies, and/or the Applicable Law, YOURSAY reserves
              the tight to take action against You and any other remedies it may
              have under the Terms, Policies and Applicable Law.
            </li>
            <li className="mb-2">
              You may opt to de-activate, cancel, or terminate Your Account and
              use of any Services by providing written notice of a request for
              Your Account’s deactivation by submitting a de-activation request
              form to YOURSAY in accordance with the Account de-activation
              process facilitated by YOURSAY on the Platform.
            </li>
            <li className="mb-2">
              You acknowledge and accept that upon termination of Your Account
              for any reason, Your agreement with Us shall be terminated, and
              You shall no longer be entitled to access Your Account or avail
              Services. You agree and acknowledge that Your rights in respect of
              the Services, and other benefits, associated with the Account may
              be irrevocably lost and agree that You will release YOURSAY of any
              liability of any nature in respect to the loss of the same. You
              further acknowledge and accept that in the event of termination of
              these Terms in any manner or suspension or termination of Your
              access to the Platform and/or the Services, or deactivation or
              cancellation of Your Account, You shall remain liable for all
              activity conducted with or in connection with Your Account and for
              all amounts due/charges incurred by Your Account while it was in
              operation at all times. The obligations and liabilities incurred
              by You prior to the termination, shall survive termination of Your
              Account and agreement with YOURSAY.
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">
            8. MARKETING AND PROMOTION
          </h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              We may send You promotional or marketing information from time to
              time, or information regarding any new and additional features
              added to the Game, Services and the Platform, updates and offers
              for User(s), and other information which may be of interest to
              You. By agreeing to these Terms and by registering an Account on
              the Platform, You hereby give Your consent to being sent such
              information by YOURSAY, such as through email or text message or
              otherwise. If, however, You do not wish to receive such
              information, You can request to opt-out of such marketing
              communication sent by YOURSAY by contacting Us at{" "}
              <b>[support@yoursay.live].</b>
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">
            9. INTELLECTUAL PROPERTY
          </h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              Unless expressly provided or disclaimed otherwise in these Terms
              or any applicable Policies or under any other disclaimer published
              on the Platform, all material and content on the Platform
              including without limitation, texts, software, code, scripts,
              graphics, rights in get-ups, typographic typefaces, graphic user
              interface, photos, collages, sounds, music, audio, videos,
              interactive content, and the like, online databases, copyright,
              patents, related rights and moral rights, trademarks, trade names,
              product names, service marks, logos, rights in domain names,
              social media handles, rights in the design, rights in the
              information and all other or equivalent rights subsisting now or
              in future in any part of the world in each case, whether
              registered or unregistered, and all applications for the same
              (collectively <b>‘Intellectual Property’</b>), are owned by or
              licensed to YOURSAY and are provided to You on an “as is” basis
              for Your information and use only for the purpose of rendering
              Services mentioned herein. Nothing in the Terms assigns, transfers
              or grants You ownership in YOURSAY’s Intellectual Property and
              nothing in these Terms shall be deemed to confer ownership or
              other rights in the Intellectual Property to the User.{" "}
            </li>
            <li className="mb-2">
              You shall not use any device, program, algorithm or methodology,
              or any manual or digital process, to access, acquire, copy or
              monitor any portion of the Platform or any content, such as the
              Game and other Intellectual Property on the Platform to which You
              have no rights, or in any way reproduce or circumvent the
              navigational structure or presentation of the Platform or any such
              content, to obtain or attempt to obtain any materials, documents
              or information through any means not purposely made available
              through the Platform. You shall not directly or indirectly copy,
              reproduce, sell, distribute, exploit, or use all or any part of
              the Platform and/or Services whether electronically, mechanically,
              or otherwise, in any form for any purpose not expressly permitted
              by the provisions of these Terms, including any attempt to violate
              the security thereof. You shall not reverse engineer, decompile,
              disassemble or otherwise attempt to derive source code or other
              trade secrets from the Platform / Services, including any of the
              software comprising or in any way making up a part of the same.{" "}
            </li>
            <li className="mb-2">
              All rights and interest in Intellectual Property comprised in the
              Game and the Platform and Services are and will remain the
              exclusive property of YOURSAY and its licensors (as may be
              applicable). You acknowledge and agree that all worldwide rights,
              title, and interest in any third-party software, products, and/or
              services (and any Intellectual Property Rights therein) which are
              accessible on the Platform or through the Services, subject to
              third party licenses, if any, are owned by such third parties. Any
              copying or reproduction of these materials for commercial purposes
              without Our consent is prohibited. Any use for which You receive
              any remuneration, whether monetarily or otherwise, is construed as
              commercial use for the purpose of this clause and YOURSAY shall
              hold You accountable for the infringement of intellectual property
              rights under Applicable Law.{" "}
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">10. INDEMNIFICATION</h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              To the extent permitted by the Applicable Law, YOURSAY shall not
              be liable to You for any manner of damages or losses to You, and
              in relation, to any person(s) or property (including special,
              incidental, indirect, punitive, or consequential damages or
              losses) including, but not limited to, lost profits or data,
              whether based in contract, negligence, tort, Applicable Law,
              arising directly or indirectly in relation to the Terms, Policies,
              the Platform, Game and Services (and any related activities,
              omissions, interruptions, deletions or defects in the same
              including any action in connection with an investigation by
              YOURSAY or law enforcement authorities in relation to the use of
              the Platform and/or Services) in accordance with these Terms, even
              if advised of the possibility of such damages. In no event shall
              YOURSAY be held liable for damages, loss, or cause of action that
              exceeds the total value of the monetary amount paid by You to
              YOURSAY for access and use of the Game offered on the Platform.
            </li>
            <li className="mb-2">
              You agree to indemnify, defend and hold harmless YOURSAY from and
              against any claims (including any claims based on publicity
              rights, defamation, or invasion of privacy), proceeding, loss,
              damage, liability, cost, demand or expense (including but not
              limited to attorney's fees) of any kind arising out of: (i) Your
              access to or use of the Platform and Services; (ii) any breach by
              You of Your obligations, representations, and/or warranties
              outlined in these Terms, Policies (iii) Your violation of the
              rights of any third party, including any infringement of
              intellectual property, or of any privacy or consumer protection
              right; (iv) any violation of law or contractual obligation and any
              claims, demands, notices pursuant to such violation; (v) Your
              negligence or willful misconduct or any of Your actions and
              omissions including Your use or attempted use of the Platform and
              its Services, or failure to take appropriate action where relevant
              while using the Services and Platform. It is clarified that Your
              obligation to indemnify YOURSAY will survive termination of the
              Terms, Policies and Your Account for any reason, in the manner
              mentioned in these Terms.{" "}
            </li>
            <li className="mb-2">
              You hereby agree and acknowledge that YOURSAY shall not be
              responsible for any actions taken by any third party using the
              Platform including but not limited to, actions, omissions, or
              conduct of such third-parties (including the Business Partners and
              other Users), online or offline. You acknowledge and agree that
              any disputes, complaints or grievances regarding the actions and
              omissions of such third-parties and/or any other aspect of any
              transaction or other commercial dealings between You and such
              third party will be solely and entirely between You and the
              relevant third-party.{" "}
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">11. DISPUTE RESOLUTION</h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              The courts of competent jurisdiction at [ Delhi, India]
              (‘Court(s)’) shall have exclusive jurisdiction to determine any
              and all matter(s), claim(s) or dispute(s), whether contractual or
              non-contractual arising out of, or in connection with, the Terms,
              Policies, the Platform, Game and Services provided by Us
              (‘Dispute(s)’). All Disputes shall be governed and construed by
              the Courts in accordance with the Applicable Law and any order,
              decree, direction, or award of the Courts shall be final and
              binding in relation to any Dispute concerning YOURSAY. Any dispute
              that may arise between You and any third party arising from Your
              use of the Game and Services shall be only between You and the
              third party and You release YOURSAY and YOURSAY Entities from any
              such claims and damages connected with such disputes. Nothing
              contained in these terms shall prevent YOURSAY from seeking and
              obtaining interim or permanent equitable or injunctive relief, or
              any other relief available to safeguard Our interest prior to,
              during or following the filing of any proceedings. The pursuit of
              equitable or injunctive relief shall not constitute a waiver on
              Our part to pursue any remedy for monetary damages. You consent to
              the exclusive jurisdiction of the Courts and waive any objection
              as to inconvenient forum.{" "}
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">12. GENERAL</h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              The Terms read along with applicable Policies (including the
              Privacy Policy) constitute the entire agreement between You and
              YOURSAY in respect of the subject matter herein and supersedes all
              previous written or oral representations, agreements, and
              understandings between You and YOURSAY, whether expressed or
              implied, with respect to such subject matter.
            </li>
            <li className="mb-2">
              Each of the provisions of the Terms is severable. If any provision
              of the Policies (or part of a provision) is found by a
              governmental authority or court to be invalid, unenforceable, or
              illegal, that provision will be enforced to the maximum extent
              permissible under by the Applicable Law and the other provisions
              of the Terms will remain in full force and effect. If any invalid,
              unenforceable or illegal provision would be valid, enforceable, or
              legal if some part of it were deleted or modified, the provision
              will apply with whatever modification is necessary to give effect
              to the intention of provisions in these Terms.{" "}
            </li>
            <li className="mb-2">
              You shall not, without the prior written consent of YOURSAY,
              assign the provisions of these Terms, in whole or part, either
              voluntarily or by operation of Applicable Law, and any attempt to
              do so will be a material default of these Terms and such
              assignment will be void. YOURSAY may assign the provisions of
              these Terms in part or in their entirety, including Our rights,
              interests, and obligations hereunder, without notice to You or
              Your consent. The provisions of these Terms are solely for the
              benefit of You and YOURSAY, YOURSAYs successors and permitted
              assigns, and does not confer any rights or remedies on any other
              person or entity.{" "}
            </li>
            <li className="mb-2">
              No failure or delay by YOURSAY in exercising any right, power or
              remedy under these Terms shall operate as a waiver thereof, nor
              shall any single or partial exercise of the same preclude any
              further exercise thereof or the exercise of any other right, power
              or remedy. Without limiting the foregoing, no waiver by YOURSAY of
              any breach of any provision of the Policies shall be deemed to be
              a waiver of any subsequent breach of that or any other provision
              of the Terms. If We fail to enforce any aspect of these Terms,
              including reporting any illegal or impermissible actions to
              appropriate law enforcement authorities or blocking or suspending
              Your Account, such failure to enforce Our rights will not be a
              waiver by Us.{" "}
            </li>
            <li className="mb-2">
              YOURSAY shall not be liable for damages for any delay or failure
              to perform its obligations hereunder, if such delay or failure is
              due to causes which are unforeseen or beyond its control,
              including, without limitation, internet attacks, emergencies,
              internet unavailability, any law, proclamation, regulation,
              ordinance, or other act or order of any court, government or
              governmental agency, acts or omissions of carriers, transmitters,
              providers, or acts of vandals or hackers, etc. The time for
              performance of such obligations of YOURSAY will be extended for
              the period of the delay or failure to perform due to such
              occurrence. YOURSAY shall use reasonable endeavors to overcome the
              effects of any such causes and to ensure resumption of normal
              performance of obligations as soon as reasonably practicable,
              however, it is clarified that YOURSAY is not responsible for
              losses that were not foreseeable to You and YOURSAY when these
              Terms were entered into.{" "}
            </li>
            <li className="mb-2">
              Any provisions in the Terms or Policies which are expressly
              referred to as surviving or intended to survive by their nature
              will survive the termination of Your Account and relationship with
              YOURSAY for any reason.{" "}
            </li>
            <li className="mb-2">
              You shall be responsible for payment of all fees/costs/charges
              associated with availing of Services from Us. You agree and
              acknowledge You responsibility to bear all applicable taxes
              duties, cess, etc. per the Applicable Laws. You agree to provide
              such further information, documents or instruments, and take such
              further actions, reasonably requested by YOURSAY, to effect the
              purposes of these Terms and carry out its provisions.{" "}
            </li>
          </ul>
          <h2 className="text-xl font-semibold mb-4">
            13. GRIEVANCE REDRESSAL
          </h2>
          <ul className="list-disc list-inside mb-6">
            <li className="mb-2">
              Any User or aggrieved person (including persons acting on their
              behalf) can address any Grievance (as defined herein above) to our
              designated resident grievance officer, the name and contact
              details of whom are published hereinbelow{" "}
              <b>(‘Resident Grievance Officer’): </b> <br />
              <b>Name:</b>[Anshu Amulani] <br />
              <b>E-mail Address:</b> [anshu@yoursay.live]{" "}
            </li>
            <li className="mb-2">
              Our Resident Grievance Officer is the nodal contact to receive and
              acknowledge all complaints as well as receive and acknowledge any
              order, notice or direction of a court, the government, or its
              agency subject to the Rules. You will receive an acknowledgement
              e-mail within 24 (twenty-four) hours upon receipt of Your
              Grievance by Our Grievance Officer. Our Grievance Officer shall
              dispose of such complaint within a period of 15 (fifteen) days
              from the date of its receipt, provided that the Grievance Officer
              may request the complainant to furnish additional information for
              evidentiary and investigative purposes during this time. However,
              We shall enable the complainant to track the status of a Grievance
              by allocating a unique ticket number to every Grievance received
              by Us and providing this to the complainant.{" "}
            </li>
            <li className="mb-2">
              Relevant communication in connection with Our compliance with the
              Information Technology, 2000 and the Rules made thereunder may be
              addressed to Our designated chief compliance officer, the name and
              contact details of whom are published hereinbelow{" "}
              <b>(‘Chief Compliance Officer’): </b> <br />
              <b>Name:</b>[Anshu Amulani] <br />
              <b>E-mail Address:</b> [anshu@yoursay.live]{" "}
            </li>
            <li className="mb-2">
              Our Nodal Contact Person (as defined hereinafter) handles
              coordination with law enforcement agencies and officers and
              compliance with orders or requisitions made per Applicable Law.
              Relevant communication may be addressed to Our designated nodal
              contact person, the name and contact details of whom are published
              hereinbelow <b>(‘Nodal Contact Person’): </b>
              <br />
              <b>Name:</b>[Arjun Munjal] <br />
              <b>E-mail Address:</b> [arjun@yoursay.live]{" "}
            </li>
            <li className="mb-2">
              You can also address any communication in writing to us at our
              office located at the following address:
              <b>
                [1-E/3, First Floor, Block E 1, Jhandewalan Extension,
                Jhandewalan, New Delhi, Delhi 110055]{" "}
              </b>{" "}
            </li>
            <li className="mb-2">
              Any Feedback and/or Grievance shall be deemed to be
              non-compensatory in nature. The Company reserves the right, at its
              sole discretion, to use such information in any manner as may be
              deemed appropriate by the Company and such use shall be entirely
              unrestricted. You represent and warrant that while sharing any
              Feedback or Grievance for the Platforms, You shall not use any
              offensive, libelous, derogatory, hateful or racially or ethnically
              objectionable language in respect of such Feedback and/or
              Grievance and that any Feedback/Grievance will be shared by You in
              accordance with these Terms and the Applicable Law.{" "}
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default TermsAndCondition;
